on: create
  branches:
    - master
  tags-ignore:
    - *.beta*
    - *.rc*
    - *.RC*
name: Deploy
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: tag
      uses: actions/bin/filter@master
      with:
        args: tag
    - name: WordPress Plugin Deploy
      uses: rtCamp/action-wordpress-org-plugin-deploy@master
      env:
        CUSTOM_COMMAND: composer install --no-dev --optimize-autoloader && npm install
          && gulp build
        EXCLUDE_LIST: asset_sources .gitignore gulpfile.js package.json package-lock.json
          README.md vendor
        SLUG: post-contributor
        WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
        WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
